### ISSUE TITLE
Add band-pass filtering process

### ISSUE THREAD

**Issue by benjamindeleener** [PolyCortex/pyMuse#15]
One way to do it would be to use scipy.signal library: http://docs.scipy.org/doc/scipy/reference/signal.html#filtering

This new process should be implemented in processes.py: https://github.com/PolyCortex/pyMuse/blob/master/pymuse/processes.py

**Comment by benjamindeleener** [comment]
Here are two great examples of butter filtering using scipy:

https://scipy.github.io/old-wiki/pages/Cookbook/ButterworthBandpass

http://stackoverflow.com/questions/12093594/how-to-implement-band-pass-butterworth-filter-with-scipy-signal-butter

**Comment by alexandreDM94** [comment]
I've tried writing a band-pass filtering - well any kind of filter actually - process as shown in the examples, though it could probably be improved. Let me know what should be changed, since you know I'm beginning with Python!

**Comment by benjamindeleener** [comment]
Done!
