### ISSUE TITLE
muse-io doesn't work with Muse2016 model

### ISSUE THREAD

**Issue by mayeaux** [PolyCortex/pyMuse#18]
It seems because of a change in how Bluetooth works, the Muse2016 can't pair with a MacBook/work with muse-io , am I right in asserting that?

**Comment by benjamindeleener** [comment]
@mrmayfield thanks for your interest. You are right! pyMuse gets the data sent by `MuseIO` via OSC messages and Muse2016 doesn't support `MuseIO`. We haven't tested it as we don't have any Muse2016.

It would be nice to bypass `MuseIO` and integrate Bluetooth support directly into pyMuse. We will work on it!

**Comment by mayeaux** [comment]
Thanks for the response. I am able to get those OSC signals via the Muse Monitor app though. I think that's the best workaround at the moment though you still have to sidestep MuseIO. I may hack around and see what I can come up with today to patch in support, what do you think?

**Comment by benjamindeleener** [comment]
Indeed, that's a proper solution for now. We have recently introduced a new processing pipeline framework that is quite powerful but that is not completely tested and integrated as it is still under development. We will probably continue to work on it in the next few months. You can take a look into the file `test_ttih.py` to see how to use it while we document it.

If you only need to extract data from the Muse without processing, you can bypass the pipeline and fetch the data from the IO. Any feedback would be helpful for us, although the development is still very preliminary!
